function New-AppGetterInstallScript {
    param(
        [string]$PackageId,
        [string]$DisplayName,
        [string]$Version,
        [string]$InstallCommand
    )

    return @"
# Install script for $DisplayName
# Intune Win32 app deployment - generated by AppGetter

`$ErrorActionPreference = 'Stop'
`$packageId = '$PackageId'
`$displayName = '$DisplayName'
`$expectedVersion = '$Version'
`$logPath = "`$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\`$packageId-install.log"

Start-Transcript -Path `$logPath -Force
Write-Host "Starting install for `$displayName (`$packageId) version `$expectedVersion"

try {
    `$scriptRoot = Split-Path -Parent `$MyInvocation.MyCommand.Path
    Set-Location -Path `$scriptRoot

    `$installCommand = @'
$InstallCommand
'@

    Write-Host "Executing install command: `$installCommand"
    `$process = Start-Process -FilePath 'cmd.exe' -ArgumentList "/c `$installCommand" -Wait -PassThru -NoNewWindow

    switch (`$process.ExitCode) {
        0 { Write-Host 'Install completed successfully.'; Stop-Transcript; exit 0 }
        3010 { Write-Host 'Install completed successfully (reboot required - 3010).'; Stop-Transcript; exit 3010 }
        1641 { Write-Host 'Install completed successfully (hard reboot required - 1641).'; Stop-Transcript; exit 1641 }
        1618 { Write-Host 'Another installation is already in progress (1618).'; Stop-Transcript; exit 1618 }
        default {
            Write-Host "Install failed with exit code `$(`$process.ExitCode)"
            Stop-Transcript
            exit `$process.ExitCode
        }
    }
}
catch {
    Write-Host "Install error: `$_"
    Stop-Transcript
    exit 1
}
"@
}

function New-AppGetterDetectionScript {
    param(
        [string]$PackageId,
        [string]$DisplayName,
        [string]$Version
    )

    $firstWord = ($DisplayName -split '\s+')[0]
    $packageLower = $PackageId.ToLower()

    return @"
# Registry-based detection script for $DisplayName
# Intune Win32 app deployment - generated by AppGetter

`$ErrorActionPreference = 'Continue'
`$packageId = '$PackageId'
`$version = '$Version'
`$displayName = '$DisplayName'
`$logPath = "`$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\`$packageId-detection.log"

Start-Transcript -Path `$logPath -Force
Write-Host "Starting `$packageId `$version detection (registry-based)"

`$registryPaths = @(
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
    'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
)

`$allMatchingVersions = @()

foreach (`$regPath in `$registryPaths) {
    try {
        `$allKeys = Get-ItemProperty `$regPath -ErrorAction SilentlyContinue
        if (-not `$allKeys) { continue }

        `$searchTerms = @('*$DisplayName*', '*$firstWord*', '*$packageLower*')
        `$uninstallKeys = `$allKeys | Where-Object {
            `$key = `$_
            foreach (`$term in `$searchTerms) {
                if ((`$key.DisplayName -and `$key.DisplayName -like `$term) -or (`$key.PSChildName -and `$key.PSChildName -like `$term)) {
                    return `$true
                }
            }
            return `$false
        }

        foreach (`$key in `$uninstallKeys) {
            Write-Host "Found registry key: `$(`$key.PSChildName) | DisplayName: `$(`$key.DisplayName) | DisplayVersion: `$(`$key.DisplayVersion)"

            if (`$key.DisplayName -like '*$DisplayName*' -and `$key.DisplayVersion) {
                `$allMatchingVersions += @{
                    DisplayName = `$key.DisplayName
                    DisplayVersion = `$key.DisplayVersion
                }
            }
        }
    }
    catch {
        Write-Host "Error checking registry path `$regPath : `$_"
    }
}

if (`$allMatchingVersions.Count -eq 0) {
    Write-Host "`$packageId not detected in registry, exiting with code 1"
    Stop-Transcript
    exit 1
}

`$installedVersion = if (`$allMatchingVersions.Count -eq 1) {
    `$allMatchingVersions[0].DisplayVersion
} else {
    (`$allMatchingVersions | Sort-Object { try { [version]`$_.DisplayVersion } catch { [version]'0.0.0' } } -Descending | Select-Object -First 1).DisplayVersion
}

Write-Host "Detected version: `$installedVersion"

if ([string]::IsNullOrWhiteSpace(`$version) -or `$version -eq 'latest') {
    Stop-Transcript
    exit 0
}

try {
    if ([version]`$installedVersion -ge [version]`$version) {
        Write-Host "`$packageId is installed with version `$installedVersion (>= expected `$version)"
        Stop-Transcript
        exit 0
    }
    Write-Host "`$packageId installed version `$installedVersion is lower than expected `$version"
    Stop-Transcript
    exit 1
}
catch {
    if (`$installedVersion -ge `$version) {
        Stop-Transcript
        exit 0
    }
    Stop-Transcript
    exit 1
}
"@
}

function New-AppGetterUninstallScript {
    param(
        [string]$PackageId,
        [string]$DisplayName
    )

    return @"
# Uninstall script for $DisplayName
# Intune Win32 app deployment - generated by AppGetter

`$ErrorActionPreference = 'Stop'
`$packageId = '$PackageId'
`$displayName = '$DisplayName'
`$logPath = "`$env:ProgramData\Microsoft\IntuneManagementExtension\Logs\`$packageId-uninstall.log"

Start-Transcript -Path `$logPath -Force
Write-Host "Starting uninstall for `$displayName (`$packageId)"

`$registryPaths = @(
    'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
    'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
)

`$uninstallString = `$null
`$quietUninstallString = `$null

foreach (`$regPath in `$registryPaths) {
    try {
        `$uninstallKeys = Get-ItemProperty `$regPath -ErrorAction SilentlyContinue | Where-Object {
            `$_.DisplayName -like '*$DisplayName*' -or
            `$_.PSChildName -like '*$($PackageId.ToLower())*' -or
            `$_.PSChildName -like '*$PackageId*'
        }

        foreach (`$key in `$uninstallKeys) {
            if (`$key.DisplayName -like '*$DisplayName*' -or `$key.DisplayName -eq `$displayName) {
                `$uninstallString = `$key.UninstallString
                `$quietUninstallString = `$key.QuietUninstallString
                Write-Host "Found uninstall string: `$uninstallString"
                break
            }
        }
        if (`$uninstallString) { break }
    }
    catch {
        Write-Host "Error checking registry path `$regPath : `$_"
    }
}

if (-not `$uninstallString) {
    Write-Host 'Uninstall string not found in registry.'
    Stop-Transcript
    exit 1
}

`$uninstallCmd = if (`$quietUninstallString) { `$quietUninstallString } else { `$uninstallString }
if (`$uninstallCmd -notmatch '/S' -and `$uninstallCmd -match '\.exe') {
    `$uninstallCmd = `$uninstallCmd -replace '"([^"]+\.exe)"', '"`$1" /S'
    Write-Host 'Added /S flag for silent uninstall'
}

Write-Host "Executing uninstall command: `$uninstallCmd"

try {
    `$process = Start-Process -FilePath 'cmd.exe' -ArgumentList "/c `$uninstallCmd" -Wait -PassThru -NoNewWindow
    if (`$process.ExitCode -eq 0 -or `$process.ExitCode -eq 3010) {
        Write-Host 'Uninstall completed successfully.'
        Stop-Transcript
        exit 0
    }
    Write-Host "Uninstall returned exit code: `$(`$process.ExitCode)"
    Stop-Transcript
    exit `$process.ExitCode
}
catch {
    Write-Host "Uninstall error: `$_"
    Stop-Transcript
    exit 1
}
"@
}

function New-AppGetterReadmeMarkdown {
    param(
        [pscustomobject]$PackageDetails,
        [string]$InstallerFileName,
        [string]$InstallerHash,
        [string]$IntuneWinFileName,
        [string]$InstallerInstallCommand,
        [string]$UninstallCommandLine,
        [string]$FinalDownloadUrl,
        [string]$DetectionType,
        [bool]$HasIcon,
        [pscustomobject]$SwitchDiscoveryResult,
        [pscustomobject]$LicenseInfo
    )

    $generatedAt = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $installCommandLine = Get-IntuneInstallCommandLine

    $licenseTypeLabel = if ($LicenseInfo -and $LicenseInfo.LicenseType) { $LicenseInfo.LicenseType } else { 'Unknown' }
    $licensingSection = ''
    if ($LicenseInfo) {
        $licenseSourceLabel = switch ([string]$LicenseInfo.Source) {
            'provided' { 'Provided (e.g. ServiceNow licensing field)' }
            'detected' { 'Detected by AppGetter license-pattern discovery' }
            default    { 'Not identified (defaulted)' }
        }
        $licenseReviewLabel = if ($LicenseInfo.NeedsManualReview) { 'Yes' } else { 'No' }
        $licenseEvidenceLines = if (@($LicenseInfo.EvidenceSummary).Count -gt 0) {
            (@($LicenseInfo.EvidenceSummary) | ForEach-Object { "- $_" }) -join "`n"
        } else {
            '- None'
        }

        $licensingSection = @"

## Licensing

| Field | Value |
|---|---|
| **License type** | $licenseTypeLabel |
| **License name** | $(if ($LicenseInfo.LicenseName) { $LicenseInfo.LicenseName } else { '-' }) |
| **License URL** | $(if ($LicenseInfo.LicenseUrl) { $LicenseInfo.LicenseUrl } else { '-' }) |
| **License notes** | $(if ($LicenseInfo.Notes) { $LicenseInfo.Notes } else { '-' }) |
| **Source** | $licenseSourceLabel |
| **Confidence score** | $($LicenseInfo.ConfidenceScore) / 100 |
| **Manual review recommended** | $licenseReviewLabel |

**Evidence:**

$licenseEvidenceLines

"@
    }

    $switchDiscoverySection = ''
    if ($SwitchDiscoveryResult) {
        $verifiedLabel = if ($SwitchDiscoveryResult.Verified) { 'Yes' } else { 'No (static discovery only)' }
        $reviewLabel = if ($SwitchDiscoveryResult.NeedsManualReview) { 'Yes' } else { 'No' }
        $evidenceLines = ($SwitchDiscoveryResult.EvidenceSummary | ForEach-Object { "- $_" }) -join "`n"
        $alternativeLines = if ($SwitchDiscoveryResult.AlternativeCommands.Count -gt 0) {
            ($SwitchDiscoveryResult.AlternativeCommands | ForEach-Object { "- ``$_``" }) -join "`n"
        } else {
            '- None'
        }

        $switchDiscoverySection = @"

## Silent Install Switch Discovery

| Field | Value |
|---|---|
| **Installer family** | $($SwitchDiscoveryResult.InstallerFamily) |
| **Primary type** | $($SwitchDiscoveryResult.PrimaryType) |
| **Confidence score** | $($SwitchDiscoveryResult.ConfidenceScore) / 100 |
| **Runtime verified** | $verifiedLabel |
| **Manual review recommended** | $reviewLabel |

**Evidence:**

$evidenceLines

**Alternative commands considered:**

$alternativeLines

"@
    }

    return @"
# $($PackageDetails.DisplayName) — Intune Win32 Package

Generated by **AppGetter** on $generatedAt.

## Application Description

$($PackageDetails.Description)

## Intune Portal Upload Reference

Use this section when creating or reviewing the Win32 app in the Microsoft Intune admin center.

| Intune field | Value |
|---|---|
| **Name / Display name** | $($PackageDetails.DisplayName) |
| **Description** | $($PackageDetails.Description) |
| **Publisher** | $($PackageDetails.Publisher) |
| **Developer** | $($PackageDetails.Developer) |
| **App version / Display version** | $($PackageDetails.Version) |
| **Package ID** | ``$($PackageDetails.PackageId)`` |
| **Information URL** | $($PackageDetails.Homepage) |
| **Download URL** | $FinalDownloadUrl |
| **Install command** | ``$installCommandLine`` |
| **Uninstall command** | ``$UninstallCommandLine`` |
| **Setup file / Installer file name** | ``$InstallerFileName`` |
| **IntuneWin package file** | ``$IntuneWinFileName`` |
| **Installer SHA-256** | ``$InstallerHash`` |
| **Detection method** | $DetectionType |
| **Applicable architecture** | x64 |
| **Minimum Windows release** | Windows 10 2004 (20H1) |
| **Install behavior** | System |
| **Device restart behavior** | Based on return code |
| **Allow available uninstall** | Yes |
| **Return codes** | 0, 1707 (success); 3010, 1641 (reboot); 1618 (retry) |
| **Icon included** | $(if ($HasIcon) { 'Yes (`icon.png`)' } else { 'No' }) |
| **License type** | $licenseTypeLabel |
| **Notes** | Generated by AppGetter [Web\|$($PackageDetails.PackageId)] License: $licenseTypeLabel |

$switchDiscoverySection$licensingSection
## Package Contents

| File | Purpose |
|---|---|
| ``install.ps1`` | Silent install wrapper with Intune logging and return codes |
| ``uninstall.ps1`` | Registry-based uninstall with silent flags |
| ``detection.ps1`` | Registry-based version detection |
| ``app.json`` | AppGetter metadata export |
| ``win32LobApp.json`` | Microsoft Graph ``win32LobApp`` definition |
| ``README.md`` | This documentation file |
| ``icon.png`` | Application icon for Intune upload (if available) |
| ``sandbox-test-report.txt`` | Chat-ready Windows Sandbox test log (created after Test in Sandbox) |
| ``sandbox-failure.log`` | Sandbox failure summary written into the package folder |
| ``appgetter-packaging.log`` | Packaging run log (created on failure) |

## Install Command (raw installer)

``````powershell
$InstallerInstallCommand
``````

## Intune Command Lines

**Install (recommended for Intune):**

``````text
$installCommandLine
``````

**Uninstall (recommended for Intune):**

``````text
$UninstallCommandLine
``````

## Detection

The detection script checks Windows uninstall registry keys (64-bit and 32-bit WOW6432Node), compares installed version against ``$($PackageDetails.Version)``, and writes logs to:

``````text
%ProgramData%\Microsoft\IntuneManagementExtension\Logs\$($PackageDetails.PackageId)-detection.log
``````

## Next Steps

1. Review ``install.ps1``, ``uninstall.ps1``, and ``detection.ps1``.
2. Optionally use **Test in Sandbox** in AppGetter to confirm install, detection, and uninstall.
3. Upload ``$IntuneWinFileName`` to Intune (**Apps** → **Windows** → **Add** → **Windows app (Win32)**).
4. Use the values in the table above when completing the Intune wizard.
5. Assign the app to a test group before broad deployment.
"@
}

function New-AppGetterMetadataFiles {
    param(
        [pscustomobject]$PackageDetails,
        [string]$VersionDirectory,
        [string]$InstallerFileName,
        [string]$InstallerHash,
        [string]$InstallerInstallCommand,
        [string]$DetectionScript,
        [string]$InstallScript,
        [string]$UninstallScript,
        [string]$IconFilePath,
        [string]$FinalDownloadUrl,
        [pscustomobject]$SwitchDiscoveryResult,
        [pscustomobject]$LicenseInfo
    )

    $uninstallCommandLine = Get-IntuneUninstallCommandLine
    $installCommandLine = Get-IntuneInstallCommandLine
    $intuneWinFileName = "$([System.IO.Path]::GetFileNameWithoutExtension($InstallerFileName)).intunewin"

    $installScriptPath = Join-Path $VersionDirectory 'install.ps1'
    $uninstallScriptPath = Join-Path $VersionDirectory 'uninstall.ps1'
    $detectionScriptPath = Join-Path $VersionDirectory 'detection.ps1'
    $readmePath = Join-Path $VersionDirectory 'README.md'
    $appJsonPath = Join-Path $VersionDirectory 'app.json'
    $win32Path = Join-Path $VersionDirectory 'win32LobApp.json'

    $InstallScript | Set-Content -Path $installScriptPath -Encoding UTF8
    $UninstallScript | Set-Content -Path $uninstallScriptPath -Encoding UTF8
    $DetectionScript | Set-Content -Path $detectionScriptPath -Encoding UTF8

    $hasIcon = (Test-Path $IconFilePath)
    $readme = New-AppGetterReadmeMarkdown -PackageDetails $PackageDetails -InstallerFileName $InstallerFileName `
        -InstallerHash $InstallerHash -IntuneWinFileName $intuneWinFileName `
        -InstallerInstallCommand $InstallerInstallCommand -UninstallCommandLine $uninstallCommandLine `
        -FinalDownloadUrl $FinalDownloadUrl -DetectionType 'PowerShell script (registry-based version check)' `
        -HasIcon $hasIcon -SwitchDiscoveryResult $SwitchDiscoveryResult -LicenseInfo $LicenseInfo
    $readme | Set-Content -Path $readmePath -Encoding UTF8

    $legacyReadme = @"
Package $($PackageDetails.PackageId) $($PackageDetails.Version) from Web Download

Display name: $($PackageDetails.DisplayName)
Version: $($PackageDetails.Version)
Publisher: $($PackageDetails.Publisher)
Website: $($PackageDetails.Homepage)
Download URL: $FinalDownloadUrl
License type: $(if ($LicenseInfo -and $LicenseInfo.LicenseType) { $LicenseInfo.LicenseType } else { 'Unknown' })

Install command (Intune):
$installCommandLine

Uninstall command (Intune):
$uninstallCommandLine

See README.md for full Intune upload reference.
"@
    $legacyReadme | Set-Content -Path (Join-Path $VersionDirectory 'readme.txt') -Encoding UTF8

    $appJson = @{
        packageIdentifier    = $PackageDetails.PackageId
        displayName          = $PackageDetails.DisplayName
        description          = $PackageDetails.Description
        version              = $PackageDetails.Version
        source               = 3
        publisher            = $PackageDetails.Publisher
        informationUrl       = $PackageDetails.Homepage
        publisherUrl         = if ($PackageDetails.DeveloperUrl) { $PackageDetails.DeveloperUrl } else { $PackageDetails.Homepage }
        supportUrl           = if ($PackageDetails.SupportUrl) { $PackageDetails.SupportUrl } else { $PackageDetails.Homepage }
        installerType        = 7
        installerUrl         = $FinalDownloadUrl
        hash                 = $InstallerHash
        installCommandLine   = $installCommandLine
        uninstallCommandLine = $uninstallCommandLine
        installerFilename    = $InstallerFileName
        installerContext     = 2
        architecture         = 2
    }
    if ($LicenseInfo) {
        $appJson.licenseType = $LicenseInfo.LicenseType
        $appJson.licensing = @{
            licenseType       = $LicenseInfo.LicenseType
            licenseName       = $LicenseInfo.LicenseName
            licenseUrl        = $LicenseInfo.LicenseUrl
            notes             = $LicenseInfo.Notes
            source            = $LicenseInfo.Source
            confidenceScore   = $LicenseInfo.ConfidenceScore
            evidenceSummary   = @($LicenseInfo.EvidenceSummary)
            needsManualReview = [bool]$LicenseInfo.NeedsManualReview
        }
    }
    if ($SwitchDiscoveryResult) {
        $appJson.switchDiscovery = @{
            installerFamily     = $SwitchDiscoveryResult.InstallerFamily
            primaryType         = $SwitchDiscoveryResult.PrimaryType
            confidenceScore     = $SwitchDiscoveryResult.ConfidenceScore
            verified            = $SwitchDiscoveryResult.Verified
            needsManualReview   = $SwitchDiscoveryResult.NeedsManualReview
            evidenceSummary     = $SwitchDiscoveryResult.EvidenceSummary
            alternativeCommands = $SwitchDiscoveryResult.AlternativeCommands
            recommendedCommand  = $SwitchDiscoveryResult.RecommendedCommand
            installerHash       = $SwitchDiscoveryResult.InstallerHash
            usedCache           = [bool]$SwitchDiscoveryResult.UsedCache
            verificationMethod  = if ($SwitchDiscoveryResult.Verification -and $SwitchDiscoveryResult.Verification.Method) {
                [string]$SwitchDiscoveryResult.Verification.Method
            } else {
                $null
            }
        }

        $silentManifest = [ordered]@{
            engine              = $SwitchDiscoveryResult.InstallerFamily
            primaryType         = $SwitchDiscoveryResult.PrimaryType
            confidenceScore     = $SwitchDiscoveryResult.ConfidenceScore
            command             = $SwitchDiscoveryResult.RecommendedCommand
            verified            = [bool]$SwitchDiscoveryResult.Verified
            needsManualReview   = [bool]$SwitchDiscoveryResult.NeedsManualReview
            evidenceSummary     = @($SwitchDiscoveryResult.EvidenceSummary)
            alternativeCommands = @($SwitchDiscoveryResult.AlternativeCommands)
            installerHash       = $SwitchDiscoveryResult.InstallerHash
            usedCache           = [bool]$SwitchDiscoveryResult.UsedCache
            verificationMethod  = if ($SwitchDiscoveryResult.Verification -and $SwitchDiscoveryResult.Verification.Method) {
                [string]$SwitchDiscoveryResult.Verification.Method
            } else {
                $null
            }
            generatedAt         = (Get-Date).ToUniversalTime().ToString('o')
        }
        $silentManifest | ConvertTo-Json -Depth 8 |
            Set-Content -Path (Join-Path $VersionDirectory 'silent-switches.json') -Encoding UTF8
    }
    $appJson | ConvertTo-Json -Depth 10 | Set-Content -Path $appJsonPath -Encoding UTF8

    $detectionScriptBase64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($DetectionScript))
    $iconBase64 = ''
    $iconMimeType = 'image/png'
    if ($hasIcon) {
        $iconBytes = [System.IO.File]::ReadAllBytes($IconFilePath)
        $iconBase64 = [Convert]::ToBase64String($iconBytes)
        $detectedMimeType = Get-ImageMimeType -Bytes $iconBytes
        if ($detectedMimeType) {
            $iconMimeType = $detectedMimeType
        }
    }

    $win32LobAppJson = @{
        '@odata.type'                       = '#microsoft.graph.win32LobApp'
        description                         = $PackageDetails.Description
        developer                           = $PackageDetails.Publisher
        displayName                         = $PackageDetails.DisplayName
        informationUrl                      = $PackageDetails.Homepage
        largeIcon                           = if ($iconBase64) { @{ type = $iconMimeType; value = $iconBase64 } } else { $null }
        notes                               = "Generated by AppGetter at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') [Web|$($PackageDetails.PackageId)]$(if ($LicenseInfo -and $LicenseInfo.LicenseType) { " License: $($LicenseInfo.LicenseType)" })"
        publisher                           = $PackageDetails.Publisher
        fileName                            = $intuneWinFileName
        allowAvailableUninstall             = $true
        applicableArchitectures               = 'x64'
        detectionRules                      = @(
            @{
                '@odata.type'           = '#microsoft.graph.win32LobAppPowerShellScriptDetection'
                enforceSignatureCheck   = $false
                runAs32Bit              = $false
                scriptContent           = $detectionScriptBase64
            }
        )
        displayVersion                      = $PackageDetails.Version
        installCommandLine                  = $installCommandLine
        installExperience                   = @{
            deviceRestartBehavior = 'basedOnReturnCode'
            runAsAccount          = 'system'
        }
        minimumSupportedOperatingSystem     = @{ v10_2004 = $true }
        minimumSupportedWindowsRelease      = '2004'
        returnCodes                         = @(
            @{ returnCode = 0; type = 'success' }
            @{ returnCode = 1707; type = 'success' }
            @{ returnCode = 3010; type = 'softReboot' }
            @{ returnCode = 1641; type = 'hardReboot' }
            @{ returnCode = 1618; type = 'retry' }
        )
        setupFilePath                       = $InstallerFileName
        uninstallCommandLine                = $uninstallCommandLine
    }

    if (-not $iconBase64) {
        $win32LobAppJson.Remove('largeIcon')
    }

    $win32LobAppJson | ConvertTo-Json -Depth 10 | Set-Content -Path $win32Path -Encoding UTF8

    return [PSCustomObject]@{
        InstallScriptPath   = $installScriptPath
        UninstallScriptPath = $uninstallScriptPath
        DetectionScriptPath = $detectionScriptPath
        ReadmePath          = $readmePath
        AppJsonPath         = $appJsonPath
        Win32LobAppJsonPath = $win32Path
        IntuneWinFileName   = $intuneWinFileName
        InstallCommandLine  = $installCommandLine
        UninstallCommandLine = $uninstallCommandLine
    }
}
